-- 코드를 입력하세요
SELECT PRODUCT_CODE, (P.PRICE * SUM(O.SALES_AMOUNT)) AS SALES
FROM PRODUCT AS P INNER JOIN OFFLINE_SALE AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC ,PRODUCT_CODE ASC

# SELECT  P.PRICE, O.SALES_AMOUNT, O.SALES_DATE
# FROM PRODUCT AS P INNER JOIN OFFLINE_SALE AS O
# ON P.PRODUCT_ID = O.PRODUCT_ID
# WHERE PRODUCT_CODE='B2000001'

# SELECT PRODUCT_ID, SUM(SALES_AMOUNT)
# FROM OFFLINE_SALE
# GROUP BY PRODUCT_ID