-- 코드를 입력하세요
-- 중성화 되지 않은 ID 중 OUT에서는 중성화 됨 

SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID IN (SELECT ANIMAL_ID
         FROM ANIMAL_INS
         WHERE SEX_UPON_INTAKE LIKE 'Intact%')
    AND
    (SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%')