SELECT FLAVOR
FROM (
      SELECT FLAVOR, TOTAL_ORDER
      FROM JULY
      UNION
      SELECT FLAVOR, TOTAL_ORDER
      FROM FIRST_HALF
      ) AS A
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3;