-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER,date_format(DATE_OF_BIRTH,'%Y-%m-%d') as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE  DATE_OF_BIRTH like '%-03-%' AND GENDER ='W' AND TLNO != 'NULL'
ORDER BY MEMBER_ID asc;